server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


#nacos将要访问的微服务
service-url:
  nacos-user-service: http://nacos-payment-provider