server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true

ribbon:
  ReadTimeout: 5000

logging:
  level:
    com.yanzhen.springcloud.service.PaymentFeignService: debug