server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: false
ribbon:
  ReadTimeout: 5000

#开启配置
feign:
  hystrix:
    enabled: true
